"""Optional GitLab publishing: commit the approved Markdown on a new branch and open a merge request.

Enabled only when GITLAB_TOKEN and GITLAB_PROJECT_ID are set. Failures never block the local export.
"""
from __future__ import annotations

from urllib.parse import quote

import httpx

from app.config import settings


def is_configured() -> bool:
    return bool(settings.gitlab_token and settings.gitlab_project_id)


def create_merge_request(job_id: int, filename: str, content: str, title: str) -> dict:
    base = f"{settings.gitlab_url.rstrip('/')}/api/v4/projects/{quote(str(settings.gitlab_project_id), safe='')}"
    headers = {"PRIVATE-TOKEN": settings.gitlab_token}
    branch = f"content-engine/job-{job_id}"
    path = f"docs/{filename}"
    with httpx.Client(timeout=30, headers=headers) as client:
        project = client.get(base); project.raise_for_status()
        default = project.json().get("default_branch", "main")
        client.post(f"{base}/repository/branches", params={"branch": branch, "ref": default}).raise_for_status()
        client.post(f"{base}/repository/commits", json={
            "branch": branch, "commit_message": f"docs: {title}",
            "actions": [{"action": "create", "file_path": path, "content": content}],
        }).raise_for_status()
        mr = client.post(f"{base}/merge_requests", json={
            "source_branch": branch, "target_branch": default,
            "title": f"Docs: {title}", "description": "Generated by the AI Content & Documentation Engine. Human-approved before export.",
        })
        mr.raise_for_status()
        return {"merge_request_url": mr.json().get("web_url"), "branch": branch, "path": path}
